### ISSUE TITLE
Directories with spaces in their names break plugin

### ISSUE THREAD

**Issue by gnowland** [codeflows/vaulty#1]
If there's a space in the path the plugin breaks, indicating that you can only "decrypt one file at a time"... fixed once I renamed a parent directory, but still...

**Comment by codeflows** [comment]
Thanks for the report @gnowland, I'll look into this!

**Comment by codeflows** [comment]
@gnowland I've published Vaulty 0.1.2 which fixes this at least on my machine, please give it another try. :)

**Comment by gnowland** [comment]
Works like a charm!!! ☄️ 🔥  🎉 🙌  💥

Thanks for the quick patch.
