### ISSUE TITLE
Path to ansible.cfg not correct

### ISSUE THREAD

**Issue by anonfriese** [codeflows/vaulty#6]
Hi there,

I'm trying to use Vaulty for decrypting my Vault. Unfortunately I get the following Error:

`ENOENT: no such file or directory, open 'C:\d:\JWS\GIT\ansible-deploy\ansible.cfg'`

The path seems a bit strange. My Git-Repo "ansible-deploy" is stored on D:\ - so I don't know why the path is prepended by C:\ ....

Inside this Git-Repo there is a file ansible.cfg with the vault_password_file set, which works great in Ansible itself. My Vault is on a subdirectory conf/vault.yml. If i run the Vaulty Command i just get the error message and Code opens a blank Window instead of my vault.yml....

If I move my Repo over to the C-Drive, it doesn't seem to work much better either:

`ENOENT: no such file or directory, open 'C:\c:\JWS\GIT\ansible-deploy\ansible.cfg'`

Version Information:
vaulty 0.2
VS Code 1.12.1
Ansible 2.4.3.0 using Python 2.7.12 running inside a Docker Container with ansible-vault.bat as Wrapper in $PATH
Windows 10 1703 64bit

**Comment by codeflows** [comment]
Thanks for the bug report! I’ll have a look at this next week.

**Comment by mrackers** [comment]
I am having he same problem as described here; any updates?

**Comment by codeflows** [comment]
Unfortunately I'm no longer using Ansible myself at the moment, nor do I have a Windows setup where I could test this out. I'd really appreciate pull requests that fix this. 🤗

**Comment by Rabusek** [comment]
Same issue here, extension is useless without this bug fixed..

**Comment by codeflows** [comment]
Hi @Rabusek. I'll try to spin up a Windows VM and see if I can do something to fix this. Thanks for the heads up!

**Comment by codeflows** [comment]
@anonfriese @mrackers @Rabusek I finally had some time to spin up a Windows 10 virtual machine. I did some initial fixes for handling Windows path names and published a beta release here: https://github.com/codeflows/vaulty/releases/tag/0.2.2-windows1

If any of you have time to test it out that would be much appreciated! You can download the `.vsix` from the release page and install it in VS Code via the `Extensions: Install from VSIX...` action. Thanks!

If all goes well I'd like to do an official release soon.

**Comment by codeflows** [comment]
Released 0.3.0 with these fixes just now. Please let me know if you have any further problems. Thanks!
